### PR TITLE
Add PHPUnit tests for getSecureRandom function and create getSecureRandom API

### PR DESCRIPTION
**Pull request by johhann**
This pull request addresses both Task 1 and Task 2 as outlined in the project requirements.

#### Task 1: PHPUnit Tests
For Task 1, I've implemented PHPUnit tests to thoroughly validate the `getSecureRandom` function in `utils.php`. The test suite includes three testing cases to ensure that the random numbers generated by the function are strong and acceptable. Each test verifies different aspects of the random number generation process, including range validity, distribution, and uniqueness.

#### Task 2: getSecureRandom API
For Task 2, I've created a `getSecureRandom` API served on a PHP server. The API utilizes the `getSecureRandom` function from `utils.php` to generate secure random numbers and returns the result as a JSON response. The structure of the API is designed for simplicity and efficiency, ensuring fast response times and reliable functionality.

## Summary by CodeRabbit

- **New Features**
	- Added a requirement for `phpunit/phpunit` version `^11.1` in `composer.json`.
	- Provided instructions in `HOWTORUN.md` for setting up and running the PHP application, including installing dependencies with Composer and running tests with PHPUnit.
	- Updated `phpunit.xml` file to include configuration for PHPUnit testing.
	- Added functionality to `server.php` to handle the `/getSecureRandom` endpoint for generating secure random numbers within a specified range.
	- Enhanced `Utils` class in `utils.php` with a new `getSecureRandom` method for generating cryptographically secure random numbers with bias and preferred values support.

- **Documentation**
	- Updated `HOWTORUN.md` with detailed instructions for running the PHP application.

- **Alterations to the declarations of exported or public entities**
	- Renamed `getSecureRandom` method in `Utils` class to `getSecureRandomOld` in `utils.php`.
	- Added a new method:
	  - `static function getSecureRandom(int $min, int $max, float $bias = 0.5, array $preferredValues = []): int` in class `Utils` in `utils.php`.

### CODE REVIEW

**Comment by sam-mereb** [comment]
@johhann Where is your implementation of the random number generator? You need to implement your version

**Comment by johhann** [comment]
I didn't create one since the tasks about writing tests and creating an API server that utilize the `getSecureRandom` method in utils.php file

**Comment by sam-mereb** [comment]
Yeah, the challenge didn't specify that clearly. Please create your own function.

**Comment by johhann** [comment]
I have created new PR to generate secure random number with custom implementation.

**Pull request closed without merging**
